#remote_theme: baileythegreen/Customising-the-Unix-Experience
#url: https://baileythegreen.com
title: "baileythegreen"
repository: baileythegreen/baileythegreen.com
github: [metadata]
description: "A website."


#google_analytics: [Google Analytics tracking ID]

plugins:
 - jekyll-github-metadata

# Additionally, you may choose to set the following optional variables:

show_downloads: ["true"]
#google_analytics: [Your Google Analytics tracking ID]

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
# Please don't change it: <USERNAME>/<PROJECT> is correct.
#repository: <USERNAME>/<PROJECT>
url: "http://baileythegreen.com"

#exclude:
#  - Makefile
#  - bin/
#  - .Rproj.user/

# Turn on built-in syntax highlighting.
highlighter: rouge
